<?php

return [
    'bas_uele' => 'Bas-Uélé',
    'haut_uele' => 'Haut-Uélé',
    'ituri' => 'Ituri',
    'nord_kivu' => 'Nord-Kivu',
    'sud_kivu' => 'Sud-Kivu',
    'tshopo' => 'Tshopo',
    'kongo_central' => 'Kongo Central',
    'kasai' => 'Kasaï',
    'kasai_central' => 'Kasaï Central',
    'kasai_oriental' => 'Kasaï Oriental',
    'lomami' => 'Lomami',
    'sankuru' => 'Sankuru',
    'maniema' => 'Maniema',
    'tanganyika' => 'Tanganyika',
    'haut_lomami' => 'Haut-Lomami',
    'haut_katanga' => 'Haut-Katanga',
    'lualaba' => 'Lualaba',
    'nord_ubangi' => 'Nord-Ubangi',
    'sud_ubangi' => 'Sud-Ubangi',
    'mongala' => 'Mongala',
    'equateur' => 'Équateur',
    'tshuapa' => 'Tshuapa',
    'kwilu' => 'Kwilu',
    'kwango' => 'Kwango',
    'mai_ndombe' => 'Mai-Ndombe',
    'kinshasa' => 'Kinshasa',
];
